name: Release
on:
  push:
    branches:
      - release # or any other branch name
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # ... other steps ...
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release 