name: Test code

on: push

jobs:
  test-code:
    runs-on: ubuntu-latest
    env:
      NOTDIAMOND_API_KEY: ${{ secrets.NOTDIAMOND_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
        env:
          NOTDIAMOND_API_KEY: ${{ secrets.NOTDIAMOND_API_KEY }}
